type=script

script=/home/hadoop/spark-2.1.1-bin-hadoop2.7/bin/spark-submit \
  --conf spark.yarn.keytab=./mammut.keytab  \
  --conf spark.yarn.principal=mammut/bigdata@HADOOP.HZ.NETEASE.COM \
  --class com.netease.spark.DummyStreamingScala \
  --master yarn  \
  --deploy-mode client \
  --driver-memory 2048M \
  --executor-memory 512M \
  --executor-cores 1 \
  --queue default \
    --driver-class-path ../:./:/home/hadoop/spark-2.1.1-bin-hadoop2.7/jars:/home/hadoop/hadoop-current/etc/hadoop:/home/hadoop/hadoop-current/share/hadoop/common/*:/home/hadoop/hadoop-current/share/hadoop/common/lib/*:/home/hadoop/hadoop-current/share/hadoop/hdfs/*:/home/hadoop/hadoop-current/share/hadoop/hdfs/lib/*:/home/hadoop/hadoop-current/share/hadoop/mapreduce/*:/home/hadoop/hadoop-current/share/hadoop/mapreduce/lib/*:/home/hadoop/hadoop-current/share/hadoop/yarn/*:/home/hadoop/hadoop-current/share/hadoop/yarn/lib/*:/home/hadoop/hadoop-current/share/hadoop/tools/lib/* \
  ./spark-demo-202.jar
