type=script

script=/home/hadoop/spark-2.0.2-bin-hadoop2.7/bin/spark-submit \
  --conf spark.yarn.keytab=./mammut.keytab  \
  --conf spark.yarn.principal=mammut/bigdata@HADOOP.HZ.NETEASE.COM \
  --class com.netease.spark.DummyStreamingScala \
  --master yarn  \
  --deploy-mode client \
  --driver-memory 2048M \
  --executor-memory 512M \
  --executor-cores 1 \
  --queue default \
  --driver-class-path ../:./ \
  ./spark-demo-202.jar
